apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: ${DATABASE_USERNAME}
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      database: ${DATABASE_NAME}
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true